# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: run:|
          echo "//registry.mentormate.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "@mentormate:registry=https://registry.mentormate.com" >> ~/.npmrc
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to npm
        run: npm publish --access public
